export const storefrontRoutes = [
  { path: '/', title: 'Home' },
  { path: '/men', title: 'Men', category: true, banner: '/images/men_banner.png', tile: '/images/men-tshirt.jpg' },
  { path: '/women', title: 'Women', category: true, banner: '/images/women_banner.png', tile: '/images/women-tshirt.jpg' },
  { path: '/kids', title: 'Kids', category: true, banner: '/images/kids_banner.png', tile: '/images/kids-tshirt.jpg' },
  { path: '/baby', title: 'Baby', category: true, banner: '/images/baby_banner.png', tile: '/images/baby-newborn.jpg' },
  { path: '/unisex', title: 'Unisex', category: true, banner: '/images/unisex_banner.png', tile: '/images/men-polo.jpg' },
  { path: '/products', title: 'All products' },
  { path: '/search', title: 'Search' },
  { path: '/products/:id', title: 'Product details' },
  { path: '/cart', title: 'Shopping cart' },
  { path: '/checkout', title: 'Checkout' },
  { path: '/checkout/success', title: 'Order confirmed' },
  { path: '/favorites', title: 'Favorites' },
  { path: '/about', title: 'About' },
  { path: '/contact', title: 'Contact' },
]